use invidious::api::search;

#[tokio::test]
async fn test_search() {
  assert_eq!(
    serde_json::to_string_pretty(&search::Feature::_3d).unwrap(),
    r#""3d""#
  );

  assert_eq!(
    serde_json::to_string_pretty(&search::Feature::CreativeCommons).unwrap(),
    r#""creative_commons""#
  );

  let response = search::request(search::Parameters {
    q: Some("buck bunny".to_string()),
    sort_by: Some(search::SortBy::ViewCount),
    ..Default::default()
  })
  .await
  .unwrap();

  if let search::SchemaType::Video(s) = &response[0] {
    assert_eq!(
      s.title,
      "LOONEY TUNES (Best of Looney Toons): BUGS BUNNY CARTOON COMPILATION (HD 1080p)"
    );
    assert_eq!(s.video_id, "Q8AZ16uBhr8");
    assert_eq!(s.author, "8thManDVD.com™ Cartoon Channel");
    assert_eq!(s.author_id, "8thManDVDcom");
    assert_eq!(s.author_url, "/channel/8thManDVDcom");
  } else {
    unreachable!()
  }

  let schema = serde_json::from_str::<search::Schema>(CHANNEL_RESPONSE).unwrap();
  assert!(schema.len() == 1);

  if let search::SchemaType::Channel(s) = &schema[0] {
    assert_eq!(s.author, "Big Buck Bunny - Topic");
    assert_eq!(s.author_id, "UCOc-sIYm-eLFmMRKxJqJ3wA");
    assert_eq!(s.author_url, "/channel/UCOc-sIYm-eLFmMRKxJqJ3wA");
  } else {
    unreachable!();
  }
}

const CHANNEL_RESPONSE: &str = r#"[
    {
      "type": "channel",
      "author": "Big Buck Bunny - Topic",
      "authorId": "UCOc-sIYm-eLFmMRKxJqJ3wA",
      "authorUrl": "/channel/UCOc-sIYm-eLFmMRKxJqJ3wA",
      "authorThumbnails": [
        {
          "url": "https://yt3.ggpht.com/nA6okNWX5eQPo1XmqZIiTrfyAoGwK_cFTG_C9DdnxnKVuVzrxdp3aKc4q809dy9fb_2rCZhIHcE=s176-c-k-c0x00ffffff-no-rj-mo",
          "width": 32,
          "height": 32
        },
        {
          "url": "https://yt3.ggpht.com/nA6okNWX5eQPo1XmqZIiTrfyAoGwK_cFTG_C9DdnxnKVuVzrxdp3aKc4q809dy9fb_2rCZhIHcE=s176-c-k-c0x00ffffff-no-rj-mo",
          "width": 48,
          "height": 48
        },
        {
          "url": "https://yt3.ggpht.com/nA6okNWX5eQPo1XmqZIiTrfyAoGwK_cFTG_C9DdnxnKVuVzrxdp3aKc4q809dy9fb_2rCZhIHcE=s176-c-k-c0x00ffffff-no-rj-mo",
          "width": 76,
          "height": 76
        },
        {
          "url": "https://yt3.ggpht.com/nA6okNWX5eQPo1XmqZIiTrfyAoGwK_cFTG_C9DdnxnKVuVzrxdp3aKc4q809dy9fb_2rCZhIHcE=s176-c-k-c0x00ffffff-no-rj-mo",
          "width": 100,
          "height": 100
        },
        {
          "url": "https://yt3.ggpht.com/nA6okNWX5eQPo1XmqZIiTrfyAoGwK_cFTG_C9DdnxnKVuVzrxdp3aKc4q809dy9fb_2rCZhIHcE=s176-c-k-c0x00ffffff-no-rj-mo",
          "width": 176,
          "height": 176
        },
        {
          "url": "https://yt3.ggpht.com/nA6okNWX5eQPo1XmqZIiTrfyAoGwK_cFTG_C9DdnxnKVuVzrxdp3aKc4q809dy9fb_2rCZhIHcE=s176-c-k-c0x00ffffff-no-rj-mo",
          "width": 512,
          "height": 512
        }
      ],
      "autoGenerated": true,
      "subCount": 0,
      "videoCount": 0,
      "description": "Big Buck Bunny is a 2008 short computer-animated comedy film featuring animals of the forest, made by the Blender Institute ...",
      "descriptionHtml": "<div class=\"yt-lockup-description yt-ui-ellipsis yt-ui-ellipsis-2\" dir=\"ltr\">Big Buck Bunny is a 2008 short computer-animated comedy film featuring animals of the forest, made by the Blender Institute ...</div>"
    }
]"#;
